# Generated by Django 3.0 on 2020-02-16 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('room_type', models.CharField(max_length=10)),
                ('room_date', models.CharField(max_length=10)),
                ('room_start_time', models.CharField(max_length=10)),
                ('room_finish_time', models.CharField(max_length=10)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
