# Generated by Django 3.0 on 2020-02-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_finish_time',
            field=models.DateTimeField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_start_time',
            field=models.DateTimeField(max_length=10),
        ),
    ]
