# Generated by Django 3.0 on 2020-03-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20200216_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_date',
            field=models.DateField(max_length=20),
        ),
    ]
