# Generated by Django 3.0 on 2020-03-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20200304_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_finish_time',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_start_time',
            field=models.IntegerField(max_length=5),
        ),
    ]
